<a href="https://colab.research.google.com/github/Octa-p/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #peckage สำหรับทำงานกับข้อมูลที่เป็นตัวเลข ในรูปแบบ matrix

##**Numpy Array**

###สร้าง numpy array (matrix) จาก list

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##Matrix transpose

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### สร้าง matrix เริ่มต้น (zeros, ones)

In [8]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง Matrix random

In [11]:
np.random.randn(5,5) #randn คือ random มาจาก normal distribution ที่มี mu=0 std=1

array([[ 1.01292902, -0.17564528, -1.91460556,  0.00401248, -0.04844997],
       [-0.02157156, -1.81975588, -1.12159508, -0.78424468,  0.99870259],
       [ 0.59397868,  1.37415031, -0.5861966 ,  0.05046063, -0.77532531],
       [-2.22360278, -0.51668642,  0.32057679,  0.95120012,  0.23681117],
       [ 1.39218726,  0.62024606, -0.67972846, -0.66097792, -0.55211857]])

In [13]:
2+(5*np.random.randn(3,3)) #random มาจาก normal distribution ที่มี mu=2 std=5

array([[ 3.45033209,  6.90392312,  4.27280343],
       [ 7.98033636,  1.73642285, -1.26379975],
       [ 5.45631174, 11.51742346,  6.61873977]])

In [14]:
np.random.randint(5,11,(4,5)) #random เลขจำนวนเต็มระหว่าง [5,11) ขนาด 4 แถว 5 หลัก

array([[ 8,  6,  6, 10,  7],
       [ 6, 10,  5,  9,  7],
       [ 5, 10,  9, 10,  9],
       [ 7, 10,  8,  7,  7]])