<a href="https://colab.research.google.com/github/Octa-p/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #peckage สำหรับทำงานกับข้อมูลที่เป็นตัวเลข ในรูปแบบ matrix

##**Numpy Array**

###สร้าง numpy array (matrix) จาก list

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

##Matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### สร้าง matrix เริ่มต้น (zeros, ones)

In [7]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง Matrix random

In [10]:
np.random.randn(5,5) #randn คือ random มาจาก normal distribution ที่มี mu=0 std=1

array([[-0.80872857,  0.7434    , -0.11640868,  0.21911995,  1.5956793 ],
       [ 1.49965314, -0.10664568, -2.80742828,  1.08452965,  0.4132754 ],
       [ 1.56231307, -0.74642828,  0.41512796,  0.35377326,  0.2640835 ],
       [ 0.77841701, -0.34913095,  0.12269971,  0.79417855,  0.03953463],
       [-1.30891582, -0.85602376,  0.75677683,  0.22604539, -0.66629919]])

In [11]:
2+(5*np.random.randn(3,3)) #random มาจาก normal distribution ที่มี mu=2 std=5

array([[ 3.62286982,  2.01755253,  4.64101831],
       [-1.81352419, -8.17042307, -3.33529089],
       [ 0.31719189,  0.91291823, -4.06739746]])

In [12]:
np.random.randint(5,11,(4,5)) #random เลขจำนวนเต็มระหว่าง [5,11) ขนาด 4 แถว 5 หลัก

array([[ 9,  6,  5,  9,  6],
       [ 6,  5,  8,  8, 10],
       [ 9,  5,  9,  5,  9],
       [ 7,  6,  9,  6,  5]])

Matrix properties

In [13]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
1+np_a

array([[2, 3, 4],
       [5, 6, 7]])

In [16]:
2*np_a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [18]:
np_a + np_c #adding matrix to matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
np_a.shape

(2, 3)

In [20]:
np_c.shape

(2, 3)

In [23]:
np.dot(np_a,np_c.T) #multipling matrix to matrix (a,b) x (b,c) = (a,c)

array([[28, 10],
       [73, 28]])

##Indexing & Slicing

In [24]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np_a[1,1]

5

In [27]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [28]:
np_a[0,:]

array([1, 2, 3])

##Useful functions

In [31]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.sum(np_a)

21

In [32]:
np.sum(np_a,axis=0) #เอาด้านแถวมารวมกันเป็นแถวเดียว

array([5, 7, 9])

In [33]:
np.sum(np_a,axis=1) #เอาค่าแนวตั้งมารวมกัน

array([ 6, 15])

In [34]:
np.mean(np_a)

3.5

In [37]:
np.mean(np_a,axis=0) #หา mean ของ column #column คือ หลัก

array([2.5, 3.5, 4.5])

### วนลูปเอง

In [40]:
sum_all = 0

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]} sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1 sum_all=1
we are at row=0,col=1 np_a[0,1]=2 sum_all=3
we are at row=0,col=2 np_a[0,2]=3 sum_all=6
we are at row=1,col=0 np_a[1,0]=4 sum_all=10
we are at row=1,col=1 np_a[1,1]=5 sum_all=15
we are at row=1,col=2 np_a[1,2]=6 sum_all=21
21


np.sum(np_a,axis=0)



In [41]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


Quiz กลุ่ม

วนลูปหาค่า
* ```np.sum(np_a,axis=1)```
* ```np.mean(np_a)```
* ```np.mean(np_a,axis=0)```
* ```np.mean(np_a,axis=1)```
* ```np.max(np_a)```
* ```np.max(np_a,axis=0)```
* ```np.max(np_a,axis=1)```
* ```np.min(np_a)```
* ```np.min(np_a,axis=0)```
* ```np.min(np_a,axis=1)```

```np.sum(np_a,axis=1)```

In [47]:
sum_all = np.zeros(np_a.shape[0])

for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[row] = sum_all[row] + np_a[row,col]
print(sum_all)

[ 6. 15.]


* ```np.mean(np_a)```

* ```np.mean(np_a,axis=0)```

* ```np.mean(np_a,axis=1)```

* ```np.max(np_a)```

* ```np.max(np_a,axis=0)```